/**
 * @file src/lib/constants.ts
 * @description THE SOVEREIGN DICTIONARY (SSOT) - V2.0
 */

export const SOVEREIGN_MASTER_EMAIL = "FAYZ@safar.com";

export const OFFICIAL_DOMAINS = ["@safaryat.net", "@safar-gate.com"];

export const ELITE_ROLES = ["agent", "admin", "operations_manager", "owner", "developer"] as const;
export const PROTECTED_ROUTES = ["/carrier", "/history", "/chats", "/profile", "/agent", "/admin"];

export const SOVEREIGN_GEO_REGISTRY: Record<
  string,
  { name: string; nameEn: string; flag: string; code: string; defaultCurrency: string; cities: string[] }
> = {
  JO: {
    name: "الأردن",
    nameEn: "Jordan",
    flag: "🇯🇴",
    code: "JO",
    defaultCurrency: "JOD",
    cities: ["amman", "zarqa", "irbid", "aqaba", "tafilah", "maan", "salt", "karak", "jerash", "mafraq", "ajloun", "balqa", "madaba"],
  },
  SA: {
    name: "السعودية",
    nameEn: "Saudi Arabia",
    flag: "🇸🇦",
    code: "SA",
    defaultCurrency: "SAR",
    cities: ["riyadh", "jeddah", "dammam", "mecca", "medina", "tabuk", "hail", "qassim", "abha"],
  },
  AE: {
    name: "الإمارات",
    nameEn: "UAE",
    flag: "🇦🇪",
    code: "AE",
    defaultCurrency: "AED",
    cities: ["dubai", "abudhabi", "sharjah", "ajman", "rak", "fujairah"],
  },
  IQ: { name: "العراق", nameEn: "Iraq", flag: "🇮🇶", code: "IQ", defaultCurrency: "USD", cities: ["baghdad", "basra", "erbil", "mosul", "najaf"] },
  SY: {
    name: "سوريا",
    nameEn: "Syria",
    flag: "🇸🇾",
    code: "SY",
    defaultCurrency: "USD",
    cities: ["damascus", "aleppo", "homs", "hama", "latakia", "tartus"],
  },
  LB: { name: "لبنان", nameEn: "Lebanon", flag: "🇱🇧", code: "LB", defaultCurrency: "USD", cities: ["beirut", "tripoli", "sidon", "tyre", "zahle"] },
  EG: {
    name: "مصر",
    nameEn: "Egypt",
    flag: "🇪🇬",
    code: "EG",
    defaultCurrency: "EGP",
    cities: ["cairo", "alexandria", "giza", "sharm", "hurghada", "luxor", "aswan"],
  },
  PS: {
    name: "فلسطين",
    nameEn: "Palestine",
    flag: "🇵🇸",
    code: "PS",
    defaultCurrency: "USD",
    cities: ["gaza", "ramallah", "hebron", "nablus", "jenin"],
  },
};
// const CITY_NAMES: Record<string, string> = {
//   amman: "عمّان",
//   zarqa: "الزرقاء",
//   irbid: "إربد",
//   aqaba: "العقبة",
//   tafilah: "الطفيلة",
//   maan: "معان",
//   salt: "السلط",
//   karak: "الكرك",
//   jerash: "جرش",
//   mafraq: "المفرق",
//   ajloun: "عجلون",
//   balqa: "البلقاء",
//   madaba: "مأدبا",
//   riyadh: "الرياض",
//   jeddah: "جدة",
//   dammam: "الدمام",
//   mecca: "مكة المكرمة",
//   medina: "المدينة المنورة",
//   tabuk: "تبوك",
//   hail: "حائل",
//   qassim: "القصيم",
//   abha: "أبها",
//   dubai: "دبي",
//   abudhabi: "أبو ظبي",
//   scrollarea: "الشارقة",
//   ajman: "عجمان",
//   rak: "رأس الخيمة",
//   fujairah: "الفجيرة",
//   cairo: "القاهرة",
//   alexandria: "الإسكندرية",
//   giza: "الجيزة",
//   sharm: "شرم الشيخ",
//   hurghada: "الغردقة",
//   luxor: "الأقصر",
//   aswan: "أسوان",
//   beirut: "بيروت",
//   tripoli: "طرابلس",
//   sidon: "صيدا",
//   tyre: "صور",
//   zahle: "زحلة",
//   damascus: "دمشق",
//   aleppo: "حلب",
//   homs: "حمص",
//   hama: "حماة",
//   latakia: "اللاذقية",
//   tartus: "طرطوس",
//   baghdad: "بغداد",
//   basra: "البصرة",
//   erbil: "أربيل",
//   mosul: "الموصل",
//   najaf: "النجف",
//   istanbul: "إسطنبول",
//   ankara: "أنقرة",
//   izmir: "إزمير",
//   antalya: "أنطاليا",
//   kuwait: "الكويت",
//   ahmadi: "الأحمدي",
//   hawalli: "حولي",
//   manama: "المنامة",
//   muharraq: "المحرق",
//   riffa: "الرفاع",
//   doha: "الدوحة",
//   rayyan: "الريان",
//   wakrah: "الوكرة",
//   muscat: "مسقط",
//   salalah: "صلالة",
//   sohar: "صحار",
// };
// export function getCityName(cityKey: string, locale: string): string {
//   if (!cityKey) return "غير محدد";
//   const lowerKey = cityKey.toLowerCase().trim();
//   return CITY_NAMES[lowerKey] || cityKey;
// }
const CITY_NAMES_AR: Record<string, string> = {
  amman: "عمّان",
  zarqa: "الزرقاء",
  irbid: "إربد",
  aqaba: "العقبة",
  tafilah: "الطفيلة",
  maan: "معان",
  salt: "السلط",
  karak: "الكرك",
  jerash: "جرش",
  mafraq: "المفرق",
  ajloun: "عجلون",
  balqa: "البلقاء",
  madaba: "مأدبا",
  riyadh: "الرياض",
  jeddah: "جدة",
  dammam: "الدمام",
  mecca: "مكة المكرمة",
  medina: "المدينة المنورة",
  tabuk: "تبوك",
  hail: "حائل",
  qassim: "القصيم",
  abha: "أبها",
  dubai: "دبي",
  abudhabi: "أبو ظبي",
  sharjah: "الشارقة",
  ajman: "عجمان",
  rak: "رأس الخيمة",
  fujairah: "الفجيرة",
  cairo: "القاهرة",
  alexandria: "الإسكندرية",
  giza: "الجيزة",
  sharm: "شرم الشيخ",
  hurghada: "الغردقة",
  luxor: "الأقصر",
  aswan: "أسوان",
  beirut: "بيروت",
  tripoli: "طرابلس",
  sidon: "صيدا",
  tyre: "صور",
  zahle: "زحلة",
  damascus: "دمشق",
  aleppo: "حلب",
  homs: "حمص",
  hama: "حماة",
  latakia: "اللاذقية",
  tartus: "طرطوس",
  baghdad: "بغداد",
  basra: "البصرة",
  erbil: "أربيل",
  mosul: "الموصل",
  najaf: "النجف",
  gaza: "غزة",
  ramallah: "رام الله",
  hebron: "الخليل",
  nablus: "نابلس",
  jenin: "جنين",
  kuwait: "الكويت",
  ahmadi: "الأحمدي",
  hawalli: "حولي",
  manama: "المنامة",
  muharraq: "المحرق",
  riffa: "الرفاع",
  doha: "الدوحة",
  rayyan: "الريان",
  wakrah: "الوكرة",
  muscat: "مسقط",
  salalah: "صلالة",
  sohar: "صحار",
  istanbul: "إسطنبول",
  ankara: "أنقرة",
  izmir: "إزمير",
  antalya: "أنطاليا",
};

const CITY_NAMES_EN: Record<string, string> = {
  amman: "Amman",
  zarqa: "Zarqa",
  irbid: "Irbid",
  aqaba: "Aqaba",
  tafilah: "Tafilah",
  maan: "Maan",
  salt: "Salt",
  karak: "Karak",
  jerash: "Jerash",
  mafraq: "Mafraq",
  ajloun: "Ajloun",
  balqa: "Balqa",
  madaba: "Madaba",
  riyadh: "Riyadh",
  jeddah: "Jeddah",
  dammam: "Dammam",
  mecca: "Mecca",
  medina: "Medina",
  tabuk: "Tabuk",
  hail: "Hail",
  qassim: "Qassim",
  abha: "Abha",
  dubai: "Dubai",
  abudhabi: "Abu Dhabi",
  sharjah: "Sharjah",
  ajman: "Ajman",
  rak: "Ras Al Khaimah",
  fujairah: "Fujairah",
  cairo: "Cairo",
  alexandria: "Alexandria",
  giza: "Giza",
  sharm: "Sharm El Sheikh",
  hurghada: "Hurghada",
  luxor: "Luxor",
  aswan: "Aswan",
  beirut: "Beirut",
  tripoli: "Tripoli",
  sidon: "Sidon",
  tyre: "Tyre",
  zahle: "Zahle",
  damascus: "Damascus",
  aleppo: "Aleppo",
  homs: "Homs",
  hama: "Hama",
  latakia: "Latakia",
  tartus: "Tartus",
  baghdad: "Baghdad",
  basra: "Basra",
  erbil: "Erbil",
  mosul: "Mosul",
  najaf: "Najaf",
  gaza: "Gaza",
  ramallah: "Ramallah",
  hebron: "Hebron",
  nablus: "Nablus",
  jenin: "Jenin",
  kuwait: "Kuwait City",
  ahmadi: "Ahmadi",
  hawalli: "Hawalli",
  manama: "Manama",
  muharraq: "Muharraq",
  riffa: "Riffa",
  doha: "Doha",
  rayyan: "Al Rayyan",
  wakrah: "Al Wakrah",
  muscat: "Muscat",
  salalah: "Salalah",
  sohar: "Sohar",
  istanbul: "Istanbul",
  ankara: "Ankara",
  izmir: "Izmir",
  antalya: "Antalya",
};

export function getCityName(cityKey: string, locale: string): string {
  if (!cityKey) return locale === "ar" ? "غير محدد" : "Unknown";
  const lowerKey = cityKey.toLowerCase().trim();
  const names = locale === "en" ? CITY_NAMES_EN : CITY_NAMES_AR;
  return names[lowerKey] || cityKey;
}
export const COUNTRY_CODE_MAP: Record<string, string> = Object.keys(SOVEREIGN_GEO_REGISTRY).reduce(
  (acc, code) => {
    const key = SOVEREIGN_GEO_REGISTRY[code].name;
    acc[key] = code;
    return acc;
  },
  {} as Record<string, string>,
);
